services:
  - type: web
    name: owe-me-identity
    runtime: image
    region: frankfurt
    plan: free
    image:
      url: ghcr.io/mrd4rkne/owe-me-identityserver/owe-me-identity:1.0.39-ge7b2356725
    dockerCommand: /bin/sh -c 'export Database__ConnectionString="Host=$Database__Host;Port=${Database__Port:-5432};Database=$Database__Database;Username=$Database__Username;Password=$Database__Password;SslMode=Require;TrustServerCertificate=true" && exec dotnet OweMe.Identity.Server.dll'
    envVars:
      # Use the exact casing that the Npgsql driver looks for inside a configuration object
      - key: Database__Host
        fromDatabase:
          name: owe-me-db
          property: host
      - key: Database__Port
        fromDatabase:
          name: owe-me-db
          property: port
      - key: Database__Database
        fromDatabase:
          name: owe-me-db
          property: database
      - key: Database__Username
        fromDatabase:
          name: owe-me-db
          property: user
      - key: Database__Password
        fromDatabase:
          name: owe-me-db
          property: password

      - key: Migrations__ApplyMigrations
        value: "true"
      - key: Migrations__SeedData
        value: "true"
      - fromGroup: dotnet-app-defaults

      - key: OweMe__Identity__ApiScopes__0__Name
        value: oweme-api
      - key: OweMe__Identity__ApiScopes__0__DisplayName
        value: oweme-api
      - key: OweMe__Identity__ApiScopes__1__Name
        value: IdentityServerApi
      - key: OweMe__Identity__ApiScopes__1__DisplayName
        value: IdentityServerApi
      - key: OweMe__Identity__Clients__0__ClientId
        value: oweme-client
      - key: OweMe__Identity__Clients__0__ClientName
        value: OweMe Client
      - key: OweMe__Identity__Clients__0__AllowedScopes__0
        value: oweme-api
      - key: OweMe__Identity__Clients__0__AllowedGrantTypes__0
        value: password
      - key: OweMe__Identity__Clients__0__ClientSecrets__0__Value
        sync: false
      - key: OweMe__Identity__Clients__1__ClientId
        value: oweme-api
      - key: OweMe__Identity__Clients__1__ClientName
        value: OweMe API
      - key: OweMe__Identity__Clients__1__AllowedScopes__0
        value: IdentityServerApi
      - key: OweMe__Identity__Clients__1__AllowedGrantTypes__0
        value: client_credentials
      - key: OweMe__Identity__Clients__1__ClientSecrets__0__Value
        sync: false
      - key: OweMe__Identity__Users__0__UserName
        value: alice
      - key: OweMe__Identity__Users__0__Password
        sync: false
