services:
  identity:
    container_name: identity
    build:
      context: .
      dockerfile: OweMe.Identity.Server/Dockerfile
    ports:
        - "8180:8180"
        - "8181:8181"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8181;http://+:8180
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1qaz@WSX
      - Serilog__WriteTo__0__Name=Console
      - Serilog__Enrich__0=WithSpan
      - ConnectionStrings__DefaultConnection=Server=oweme_identity_database;Database=OweMe.Identity;Username=sa;Password=Password123;TrustServerCertificate=True;
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - oweme_identity_database
  oweme_identity_database:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=OweMe.Identity
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Password123