services:
  oweme.identity.server:
    image: oweme.identity.server
    build:
      context: .
      dockerfile: OweMe.Identity.Server/Dockerfile
    ports:
        - "8180:8180"
        - "8181:8181"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8181;http://+:8180
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1qaz@WSX
      - Serilog__WriteTo__0__Name=Console
      - Serilog__Enrich__0=WithSpan
      - ConnectionStrings__DefaultConnection=Server=oweme_identity_database;Database=OweMe.Identity;User=sa;Password=Password123;TrustServerCertificate=True;
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - oweme_identity_database
  oweme_identity_database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    build:
      context: .
    ports:
      - "1433:1433"
    environment:
        - SA_PASSWORD=Password123
        - ACCEPT_EULA=Y
        - MSSQL_PID=Express