services:
  oweme.identity.server:
    image: oweme.identity.server
    build:
      context: .
      dockerfile: OweMe.Identity.Server/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=oweme_identity_database;Database=OweMe.Identity;User=sa;Password=Password123;TrustServerCertificate=True;
    depends_on:
      - oweme_identity_database
  oweme_identity_database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    build:
      context: .
    ports:
      - "1433:1433"
    environment:
        - SA_PASSWORD=Password123
        - ACCEPT_EULA=Y
        - MSSQL_PID=Express